Exception: STATUS_ACCESS_VIOLATION at rip=003FC71868A
rax=0000000000000000 rbx=0000000000000000 rcx=0000000000000000
rdx=0000000000000000 rsi=00000003FC93D620 rdi=00000003FC840918
r8 =00006FFFFFEA1140 r9 =00006FFFFFE80000 r10=0000000000000000
r11=00006FFFFFEA1058 r12=00006FFFFFF1BBF0 r13=0000000800041CD0
r14=0000000000000000 r15=00006FFFFFE955F0
rbp=0000000000000000 rsp=00000000FFFFC710
program=C:\cygwin64\bin\python3.8.exe, pid 418, thread main
cs=0033 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame        Function    Args
00000000000  003FC71868A (6FFFFFF1BBF0, 00000000000, 00000000000, 6FFFFFF1BBF0)
00000000000  003FC803C14 (FFFFFFFFFFFFFFFF, 000FFFFC850, AD2DF3FED7DBA6F6, 003FC6AB370)
00000000000  003FC806016 (003FC6E0FA1, 003FC83CC00, 00180335D70, 00180335D70)
00000000000  003FC6DCE57 (003FC840918, 00000000000, 6FFFFFE23B30, 00000000000)
00000000000  003FC6A2239 (6FFFFFE23B30, 00000000000, 00000000000, 6FFFFFE955F0)
00000000000  003FC6A262A (003FC6E0FA1, 0000000007F, 00000000000, 00180335D70)
00000000000  003FC6DCE57 (00000000000, 00000000000, 6FFFFFF38040, 00000000000)
00000000000  003FC6A2239 (00080335D70, 00180335D70, 6FFFFFF38040, 6FFFFFF38110)
00000000000  003FC6A2737 (003FC796248, 00000000000, 00000000000, 00000000000)
00000000000  003FC7962D2 (AD2DF3FED7DBA6F6, 00800000C70, 003FC7944F4, 00800000C70)
00000000000  003FC79655E (00000000000, 00800041C70, 6FFFFFF39C10, 00000000000)
00000000000  003FC7BA325 (001800485F2, 00100000001, 00100000006, 001004016D0)
000FFFFCCE0  003FC7BAA8B (00000000020, 8080808080808080, 00180049E91, 00180048D30)
000FFFFCCE0  00180049EFD (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047856 (00000000000, 00000000000, 00000000000, 00000000000)
000FFFFFFF0  00180047904 (00000000000, 00000000000, 00000000000, 00000000000)
End of stack trace
